#! /usr/bin/python3
import os
import shutil


home = os.path.expanduser('~')

vundle_path = os.path.join(home, ".vim", "bundle", "Vundle.vim")
vundle_repo = "https://github.com/VundleVim/Vundle.vim.git"


def setup_vim():
    if not os.path.exists(vundle_path):
        print("cloning vundle")
        os.makedirs(vundle_path)
        os.system("git clone %s %s" % (vundle_repo, vundle_path))
    print("installing vim plugins")
    os.system("vim +PluginInstall +qall")


if __name__ == '__main__':
    setup_vim()
